### ISSUE TITLE
Output to log file?

### ISSUE THREAD

**Issue by fnoop** [01org/mavlink-router#49]
Currently all output goes to stdout, so if launched from systemd then it goes into the murky journal world.
It would be nice to output to log, at least as an option.

**Comment by lucasdemarchi** [comment]
Can you just set the log location in your .service. not adding support for a file was done on purpose because of this.

**Comment by fnoop** [comment]
Erm, how can you do that?  I did look through the depths of systemd but couldn't see a way to do that.  Everything I saw indicates that logging goes to journalctl.

**Comment by lucasdemarchi** [comment]
I meant... not done on purpose because you have better ways than logging to a file, not that you are able to do that with systemd ;-). StandardOutput in systemd.exec man page gives you all the options. I usually use journal or tty or a combination thereof.

Why do you want to redirect to a file? Should we then do log rotation or overwrite what was there? Or a never-ending appending to that file? How to separate logs from last boot from the previous one? This is basically a solved problem with the journal and you can just do a "journalctl -u mavlink-routerd -b". And it controls rotation and how much space the logs can occupy, etc etc. And I can see the logs for all daemons in the system without fiddling with different locations for each of them.

**Comment by fnoop** [comment]
Ah you got me all hopeful there!
OK that's fine, I'll just have to get used to journalctl :)
